[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking = "44wtY3cLuL2rqbH2K3nMDHnjnQ4aM3L6Es8wdHqN2hnM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
